### ISSUE TITLE
'Tomjn\ComposerPress\Model' not found

### ISSUE THREAD

**Issue by cleanforestco** [Tarendai/composerpress#5]
Plugin could not be activated because it triggered a fatal error:

Class 'Tomjn\ComposerPress\Model' not found in /site/wp-content/plugins/composerpress/plugin.php on line 37

WP Version 4.5.2
Composerpress Version: 1.0

**Comment by Tarendai** [comment]
Did you run `composer install`?

**Comment by cleanforestco** [comment]
Ah sorry, I misread the instructions.
